### ISSUE TITLE
Support for optionals

### ISSUE THREAD

**Issue by markiv** [almazrafi/DictionaryCoder#22]
A decodable with an optional property cannot currently be decoded:

```swift
struct Pepe: Decodable {
    let name: String?
    let age: Int
}
```
If the dictionary was read via `JSONSerialization`, for example, the corresponding values in the dictionary are `NSNull`.

We then get the error:
"Expected to decode String but found NSNull instead."

Instead, the decoder should produce `nil` values for optional properties.

**Comment by almazrafi** [comment]
Hello 👋
NSNull decoding has been implemented: https://github.com/almazrafi/DictionaryCoder/pull/24
Thanks for reporting this problem!
